version: "3.9"
services:
  frontend:
    build: ./frontfolder
    container_name: form_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
   
  backend:
    build: ./backfolder
    container_name: form_backend

